### ISSUE TITLE
Not reproduced error in actions/checkout@v2

### ISSUE THREAD

**Issue by taikiinoue45** [taikiinoue45/PaDiM#3]
## My workflow file

```
name: merge

on:
  push:
    branches: [main]
    paths-ignore:
      - assets/**

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: taikiinoue45/mvtec:padim
          no-cache: true

      - name: Change mode
        if: always()
        run: chmod -R 777 /home/inoue/actions-runner/PaDiM/_work

  pytest:
    needs: [docker-build]
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:padim

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test checksum
        run: pytest -v tests/test_checksum.py

      - name: Test coverage
        run: |
          pytest -v --cov=padim --cov-report=xml tests/test_coverage.py
          rm -rf outputs/
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: PaDiM
          fail_ci_if_error: true

      - name: Run experiments
        run: |
          python run.py params.tracking_uri=databricks params.experiment_name=/Users/inoue@nablas.com/MVTec params.run_name=PaDiM params.category=bottle
      - name: Git add, commit, and push
        run: |
          mv outputs/*/*/*.gif assets/
          mv outputs/*/*/*_roc_curve.csv assets/
          mv outputs/*/*/*_pro_curve.csv assets/
          git config --local user.name "taikiinoue45"
          git config --local user.email "taikiinoue45@gmail.com"
          git add assets/*
          git commit -m "Update assets by github actions"
          git push origin main
      - name: Change mode
        if: always()
        run: chmod -R 777 /__w
```

## Github Actions Log

The following screenshots are from the same commit. Basically, it failed, but sometimes it succeeded. It means `not reproduced`.

`actions/checkout@v2` succeeded

![image](https://user-images.githubusercontent.com/29189728/116041636-64c0b700-a6a8-11eb-80a7-17bae4aac1c2.png)

`actions/checkout@v2` failed

![image](https://user-images.githubusercontent.com/29189728/116041727-83bf4900-a6a8-11eb-9939-329e4287cfe6.png)
